export type Barrio = {
  id: number;
  Nombre: string;
};

export const barrios: Barrio[] = [
  { id: 1, Nombre: "V.I.C.O.R." },
  { id: 2, Nombre: "ALTOS SAN MARTIN" },
  { id: 3, Nombre: "BAJADA SAN ROQUE" },
  { id: 4, Nombre: "IRUPE" },
  { id: 5, Nombre: "LOS HORNILLOS" },
  { id: 6, Nombre: "LA ESPERANZA" },
  { id: 7, Nombre: "AMPLIACION LOS ALAMOS" },
  { id: 8, Nombre: "ZEPA" },
  { id: 9, Nombre: "CIUDAD DE LOS NIÑOS" },
  { id: 10, Nombre: "VILLA RIVADAVIA ANEXO " },
  { id: 11, Nombre: "FERRER" },
  { id: 12, Nombre: "CIUDAD DE JUAN PABLO II" },
  { id: 13, Nombre: "NUEVO URCA" },
  { id: 14, Nombre: "MAURIZI" },
  { id: 15, Nombre: "ROGELIO MARTINEZ" },
  { id: 16, Nombre: "BELLA VISTA OESTE" },
  { id: 17, Nombre: "LICEO GENERAL PAZ" },
  { id: 18, Nombre: "1RA. JUNTA" },
  { id: 19, Nombre: "MANANTIALES I" },
  { id: 20, Nombre: "ALTOS SUD DE SAN VICENTE" },
  { id: 21, Nombre: "ZEPA" },
  { id: 22, Nombre: "MERCANTIL" },
  { id: 23, Nombre: "POLICIAL" },
  { id: 24, Nombre: "SAN LORENZO NORTE" },
  { id: 25, Nombre: "VILLA CORNU" },
  { id: 26, Nombre: "LAS MARGARITAS" },
  { id: 27, Nombre: "ALTO VERDE" },
  { id: 28, Nombre: "MILITAR GENERAL DEHEZA" },
  { id: 29, Nombre: "20 DE JUNIO" },
  { id: 30, Nombre: "POLICIAL" },
  { id: 31, Nombre: "LOS JOSEFINOS" },
  { id: 32, Nombre: "CACERES" },
  { id: 33, Nombre: "CUPANI" },
  { id: 34, Nombre: "LOS CHINGOLOS" },
  { id: 35, Nombre: "CASEROS" },
  { id: 36, Nombre: "CONSORCIO 16 DE NOVIEMBRE" },
  { id: 37, Nombre: "ALTO PALERMO" },
  { id: 38, Nombre: "TABLADA PARK" },
  { id: 39, Nombre: "PARQUE MONTECRISTO" },
  { id: 40, Nombre: "LOS PINOS" },
  { id: 41, Nombre: "GUIÑAZU SUD" },
  { id: 42, Nombre: "BAJADA DE PIEDRA" },
  { id: 43, Nombre: "SIN DESIGNACION" },
  { id: 44, Nombre: "AIRES DEL SUR" },
  { id: 45, Nombre: "ALTO HERMOSO" },
  { id: 46, Nombre: "SAN LUIS DE FRANCIA" },
  { id: 47, Nombre: "KAIROS" },
  { id: 48, Nombre: "YAPEYU" },
  { id: 49, Nombre: "GUAYAQUIL" },
  { id: 50, Nombre: "PATRICIOS" },
  { id: 51, Nombre: "SAN FRANCISCO" },
  { id: 52, Nombre: "AMPLIACION EMPALME" },
  { id: 53, Nombre: "PARQUE COREMA" },
  { id: 54, Nombre: "BENJAMIN POLICARPIO CABRAL" },
  { id: 55, Nombre: "PARQUE LOS MOLINOS" },
  { id: 56, Nombre: "VILLA CORINA" },
  { id: 57, Nombre: "PARQUE SAN VICENTE" },
  { id: 58, Nombre: "PASO DE LOS ANDES" },
  { id: 59, Nombre: "EJERCITO ARGENTINO" },
  { id: 60, Nombre: "COUNTRY CLUB" },
  { id: 61, Nombre: "FINCA LA DOROTEA" },
  { id: 62, Nombre: "LOS EUCALIPTUS" },
  { id: 63, Nombre: "O.S.N." },
  { id: 64, Nombre: "SUAREZ" },
  { id: 65, Nombre: "BARRANCAS DEL SUR" },
  { id: 66, Nombre: "FERREYRA SEGUNDA SECCION" },
  { id: 67, Nombre: "PATRIA" },
  { id: 68, Nombre: "CAROLA LORENZINI" },
  { id: 69, Nombre: "EL CERRITO" },
  { id: 70, Nombre: "AMPLIACION ALTAMIRA" },
  { id: 71, Nombre: "PARQUE CHATEAU CARRERAS" },
  { id: 72, Nombre: "QUINTAS DE ARGUELLO" },
  { id: 73, Nombre: "GENERAL BUSTOS" },
  { id: 74, Nombre: "AMPLIACION ROSEDAL" },
  { id: 75, Nombre: "PARQUE JORGE NEWBERY" },
  { id: 76, Nombre: "ROSEDAL" },
  { id: 77, Nombre: "RESIDENCIAL OLIVOS" },
  { id: 78, Nombre: "COLINAS DE BELLA VISTA" },
  { id: 79, Nombre: "SAN NICOLAS" },
  { id: 80, Nombre: "U.O.C.R.A." },
  { id: 81, Nombre: "CERVECEROS" },
  { id: 82, Nombre: "CERVECEROS" },
  { id: 83, Nombre: "COUNTRY LOS ALGARROBOS" },
  { id: 84, Nombre: "ALBORADA (S)" },
  { id: 85, Nombre: "CERRO CHICO" },
  { id: 86, Nombre: "LOS OLMOS SUD" },
  { id: 87, Nombre: "S.E.P." },
  { id: 88, Nombre: "O.S.N." },
  { id: 89, Nombre: "ANA MARIA ZUMARAN" },
  { id: 90, Nombre: "ALTOS DE VILLA CABRERA" },
  { id: 91, Nombre: "REMEDIOS DE ESCALADA" },
  { id: 92, Nombre: "SARGENTO CABRAL" },
  { id: 93, Nombre: "VILLA CABRERA" },
  { id: 94, Nombre: "HIPOLITO IRIGOYEN" },
  { id: 95, Nombre: "ARGUELLO" },
  { id: 96, Nombre: "GENERAL ARENALES" },
  { id: 97, Nombre: "LOS OLMOS SUD" },
  { id: 98, Nombre: "AMPLIACION FARINA" },
  { id: 99, Nombre: "MARQUES DE SOBREMONTE" },
  { id: 100, Nombre: "JERONIMO LUIS DE CABRERA" },
  { id: 101, Nombre: "JUAN B. JUSTO" },
  { id: 102, Nombre: "DEAN FUNES" },
  { id: 103, Nombre: "MARCELO T. DE ALVEAR" },
  { id: 104, Nombre: "GENERAL ARTIGAS" },
  { id: 105, Nombre: "CIUDAD OBISPO ANGELELLI" },
  { id: 106, Nombre: "ALBORADA (N)" },
  { id: 107, Nombre: "COLINAS DE VELEZ SARSFIELD" },
  { id: 108, Nombre: "PARQUE VELEZ SARSFIELD" },
  { id: 109, Nombre: "LOS PARAISOS" },
  { id: 110, Nombre: "SAN CAYETANO" },
  { id: 111, Nombre: "EMAUS" },
  { id: 112, Nombre: "LOS CEIBOS" },
  { id: 113, Nombre: "GRANADERO PRINGLES" },
  { id: 114, Nombre: "COFICO" },
  { id: 115, Nombre: "YOFRE I" },
  { id: 116, Nombre: "SANTA ISABEL 3A SECCION" },
  { id: 117, Nombre: "COMANDANTE ESPORA" },
  { id: 118, Nombre: "GENERAL MOSCONI" },
  { id: 119, Nombre: "JARDIN HIPODROMO" },
  { id: 120, Nombre: "NUEVA CORDOBA" },
  { id: 121, Nombre: "INDEPENDENCIA" },
  { id: 122, Nombre: "PARQUE FUTURA" },
  { id: 123, Nombre: "PARQUE FUTURA" },
  { id: 124, Nombre: "REMEDIOS DE ESCALADA" },
  { id: 125, Nombre: "YAPEYU" },
  { id: 126, Nombre: "ALMIRANTE BROWN" },
  { id: 127, Nombre: "CRISOL NORTE" },
  { id: 128, Nombre: "AMEGHINO NORTE" },
  { id: 129, Nombre: "LOS NARANJOS" },
  { id: 130, Nombre: "LOS PLATANOS" },
  { id: 131, Nombre: "SAN LORENZO (S)" },
  { id: 132, Nombre: "SAN LORENZO" },
  { id: 133, Nombre: "PARQUE LICEO SECCION 1" },
  { id: 134, Nombre: "CARRARA" },
  { id: 135, Nombre: "PARQUE CHACABUCO" },
  { id: 136, Nombre: "SANTA CECILIA" },
  { id: 137, Nombre: "VILLA MARTA" },
  { id: 138, Nombre: "CENTRO" },
  { id: 139, Nombre: "LA HORTENSIA" },
  { id: 140, Nombre: "VIVERO NORTE" },
  { id: 141, Nombre: "ALTOS DE MANANTIALES" },
  { id: 142, Nombre: "PARQUE LICEO 1A SECCION" },
  { id: 143, Nombre: "ARTURO CAPDEVILA" },
  { id: 144, Nombre: "VILLA SERRANA" },
  { id: 145, Nombre: "LAS ROSAS" },
  { id: 146, Nombre: "VILLA ALBERDI" },
  { id: 147, Nombre: "MARECHAL" },
  { id: 148, Nombre: "SAN MARTIN NORTE" },
  { id: 149, Nombre: "OBRERO" },
  { id: 150, Nombre: "VILLA ALLENDE PARQUE" },
  { id: 151, Nombre: "SAN MARTIN ANEXO" },
  { id: 152, Nombre: "LOMAS DE SAN MARTIN" },
  { id: 153, Nombre: "CORRAL DE PALOS" },
  { id: 154, Nombre: "PARQUE LICEO 2A SECCION" },
  { id: 155, Nombre: "SANTA RITA" },
  { id: 156, Nombre: "NUEVA ITALIA" },
  { id: 157, Nombre: "GUARNICION AREA CBA" },
  { id: 158, Nombre: "CABO FARINA" },
  { id: 159, Nombre: "CABO FARINA" },
  { id: 160, Nombre: "AMEGHINO SUD" },
  { id: 161, Nombre: "RENACIMIENTO" },
  { id: 162, Nombre: "JARDIN DEL PILAR" },
  { id: 163, Nombre: "MARCOS SASTRE" },
  { id: 164, Nombre: "VALLE CERCANO" },
  { id: 165, Nombre: "INDUSTRIAL ESTE" },
  { id: 166, Nombre: "JOSE IGNACIO DIAZ 2A SECCION" },
  { id: 167, Nombre: "VALLE DEL CERRO" },
  { id: 168, Nombre: "AMPLIACION URCA" },
  { id: 169, Nombre: "COLINAS DEL CERRO" },
  { id: 170, Nombre: "COUNTRY BARRANCAS" },
  { id: 171, Nombre: "PARQUE TABLADA" },
  { id: 172, Nombre: "VILLA ADELA" },
  { id: 173, Nombre: "AEROPUERTO" },
  { id: 174, Nombre: "LOS BOULEVARES" },
  { id: 175, Nombre: "PARQUE MODELO" },
  { id: 176, Nombre: "COUNTRY RANCH CLUB" },
  { id: 177, Nombre: "VILLA SOLFERINO" },
  { id: 178, Nombre: "ROSEDAL" },
  { id: 179, Nombre: "VILLA PAEZ" },
  { id: 180, Nombre: "CALIFORNIA" },
  { id: 181, Nombre: "EMPALME CASAS DE OBREROS Y EMPLEADOS" },
  { id: 182, Nombre: "BAJO GALAN" },
  { id: 183, Nombre: "SANTA ANA RESIDENCIAL" },
  { id: 184, Nombre: "AMPLIACION PUEYRREDON" },
  { id: 185, Nombre: "SAN JAVIER" },
  { id: 186, Nombre: "SAN JAVIER" },
  { id: 187, Nombre: "VILLA ARGENTINA" },
  { id: 188, Nombre: "VILLA ASPASIA" },
  { id: 189, Nombre: "SEP SEGUNDA ETAPA" },
  { id: 190, Nombre: "LAS HUERTILLAS" },
  { id: 191, Nombre: "FERROVIARIO  MITRE" },
  { id: 192, Nombre: "EMPALME" },
  { id: 193, Nombre: "LAS LILAS" },
  { id: 194, Nombre: "PARQUE ALAMEDA" },
  { id: 195, Nombre: "PARQUE ALAMEDA" },
  { id: 196, Nombre: "JOSE IGNACIO DIAZ 1A SECCION" },
  { id: 197, Nombre: "TALLERES SUD" },
  { id: 198, Nombre: "LAS LILAS" },
  { id: 199, Nombre: "VILLA CORNU" },
  { id: 200, Nombre: "COOPERATIVA 16 DE NOVIEMBRE" },
  { id: 201, Nombre: "TEJAS DE LA CANDELARIA" },
  { id: 202, Nombre: "SAN ANTONIO" },
  { id: 203, Nombre: "OBSERVATORIO" },
  { id: 204, Nombre: "APEADERO LA TABLADA" },
  { id: 205, Nombre: "OMBU" },
  { id: 206, Nombre: "SOLARES DE SANTA MARIA" },
  { id: 207, Nombre: "MANANTIALES II" },
  { id: 208, Nombre: "RIVADAVIA" },
  { id: 209, Nombre: "CLAROS DEL BOSQUE" },
  { id: 210, Nombre: "4 DE FEBRERO" },
  { id: 211, Nombre: "SAN PEDRO NOLASCO" },
  { id: 212, Nombre: "ALTOS DE VELEZ SARSFIELD" },
  { id: 213, Nombre: "RESIDENCIAL VELEZ SARSFIELD" },
  { id: 214, Nombre: "PARQUE ATLANTICA" },
  { id: 215, Nombre: "SAN DANIEL" },
  { id: 216, Nombre: "JARDIN ESPINOSA" },
  { id: 217, Nombre: "JOCKEY CLUB" },
  { id: 218, Nombre: "AMPLIACION JARDIN ESPINOSA" },
  { id: 219, Nombre: "JARDINES DEL JOCKEY" },
  { id: 220, Nombre: "DR REMO M. COPELLO" },
  { id: 221, Nombre: "GENERAL BELGRANO" },
  { id: 222, Nombre: "PATRICIOS OESTE" },
  { id: 223, Nombre: "LAS CAÑITAS" },
  { id: 224, Nombre: "SIN DESIGNACION" },
  { id: 225, Nombre: "OÑA" },
  { id: 226, Nombre: "PARQUE SAN CARLOS" },
  { id: 227, Nombre: "MALDONADO" },
  { id: 228, Nombre: "COLONIA LOLA" },
  { id: 229, Nombre: "PARQUE DEL ESTE" },
  { id: 230, Nombre: "ANEXO LAS PALMAS" },
  { id: 231, Nombre: "VILLA ABALOS" },
  { id: 232, Nombre: "LOS GRANADOS" },
  { id: 233, Nombre: "RESIDENCIAL SAN ROQUE" },
  { id: 234, Nombre: "CONSORCIO ESPERANZA" },
  { id: 235, Nombre: "EL TREBOL" },
  { id: 236, Nombre: "CIUDAD DE LOS CUARTETOS" },
  { id: 237, Nombre: "LAS PLAYAS" },
  { id: 238, Nombre: "A.T. E." },
  { id: 239, Nombre: "VILLA BELGRANO" },
  { id: 240, Nombre: "CERRO DE LAS ROSAS" },
  { id: 241, Nombre: "URCA" },
  { id: 242, Nombre: "ITUZAINGO II" },
  { id: 243, Nombre: "CIUDAD DE MIS SUE�OS" },
  { id: 244, Nombre: "JUAN XXIII" },
  { id: 245, Nombre: "EL QUEBRACHAL" },
  { id: 246, Nombre: "COOPERATIVA LA UNIDAD" },
  { id: 247, Nombre: "VILLA BUSTOS" },
  { id: 248, Nombre: "PARQUE CAPITAL SUR" },
  { id: 249, Nombre: "LOURDES" },
  { id: 250, Nombre: "PARQUE DON BOSCO" },
  { id: 251, Nombre: "VILLA SIBURU" },
  { id: 252, Nombre: "AMPLIACION PALMAR" },
  { id: 253, Nombre: "1ro DE MAYO" },
  { id: 254, Nombre: "VILLA BUSTOS" },
  { id: 255, Nombre: "AMPLIACION 1ro DE MAYO" },
  { id: 256, Nombre: "DEAN FUNES" },
  { id: 257, Nombre: "AMPLIACION LOS PLATANOS" },
  { id: 258, Nombre: "LAMADRID" },
  { id: 259, Nombre: "LOS JACARANDAES" },
  { id: 260, Nombre: "VILLA UNION" },
  { id: 261, Nombre: "VILLA ALBERTO" },
  { id: 262, Nombre: "BRIGADIER SAN MARTIN" },
  { id: 263, Nombre: "BETANIA" },
  { id: 264, Nombre: "MIRALTA" },
  { id: 265, Nombre: "CIUDAD EVITA" },
  { id: 266, Nombre: "PORTAL DE CORDOBA" },
  { id: 267, Nombre: "BOEDO" },
  { id: 268, Nombre: "INDUSTRIAL OESTE" },
  { id: 269, Nombre: "ARSENALES ANEXO" },
  { id: 270, Nombre: "VILLA DERNA" },
  { id: 271, Nombre: "VILLA ALBERTO ANEXO" },
  { id: 272, Nombre: "TTE. BENJAMIN MATIENZO" },
  { id: 273, Nombre: "URQUIZA" },
  { id: 274, Nombre: "COLON" },
  { id: 275, Nombre: "EL CABILDO" },
  { id: 276, Nombre: "SANTA ISABEL 2A SECCION" },
  { id: 277, Nombre: "VILLA EL LIBERTADOR" },
  { id: 278, Nombre: "CONGRESO" },
  { id: 279, Nombre: "LOS FRESNOS" },
  { id: 280, Nombre: "CHATEAU LOS ROBLES" },
  { id: 281, Nombre: "CHATEAU LOS ROBLES" },
  { id: 282, Nombre: "LA TOMA" },
  { id: 283, Nombre: "VILLA MAFEKIN" },
  { id: 284, Nombre: "ALTOS DE SANTA ANA" },
  { id: 285, Nombre: "EL PUEBLITO" },
  { id: 286, Nombre: "CHATEAU LOS ROBLES" },
  { id: 287, Nombre: "CHATEAU LOS ROBLES" },
  { id: 288, Nombre: "POETA LUGONES" },
  { id: 289, Nombre: "LAS DELICIAS" },
  { id: 290, Nombre: "VILLA ZEPPELIN" },
  { id: 291, Nombre: "AERONAUTICO" },
  { id: 292, Nombre: "BETANIA" },
  { id: 293, Nombre: "TALLERES (O)" },
  { id: 294, Nombre: "TALLERES (E)" },
  { id: 295, Nombre: "PANAMERICANO" },
  { id: 296, Nombre: "LA FRATERNIDAD" },
  { id: 297, Nombre: "RECREO DEL NORTE" },
  { id: 298, Nombre: "LOS GIGANTES" },
  { id: 299, Nombre: "VILLA AZALAIZ OESTE" },
  { id: 300, Nombre: "YOFRE SUD" },
  { id: 301, Nombre: "CENTRO AMERICA" },
  { id: 302, Nombre: "VILLA AZALAIZ" },
  { id: 303, Nombre: "AMPLIACION RESIDENCIAL AMERICA" },
  { id: 304, Nombre: "LOS ALAMOS" },
  { id: 305, Nombre: "GENERAL SAVIO" },
  { id: 306, Nombre: "QUINTA SANTA ANA" },
  { id: 307, Nombre: "ALBERDI" },
  { id: 308, Nombre: "YOFRE H" },
  { id: 309, Nombre: "YOFRE H" },
  { id: 310, Nombre: "PALMAR" },
  { id: 311, Nombre: "VILLA CLAUDINA" },
  { id: 312, Nombre: "CIUDADELA" },
  { id: 313, Nombre: "URITORCO" },
  { id: 314, Nombre: "LA RESERVA" },
  { id: 315, Nombre: "VASQUEZ" },
  { id: 316, Nombre: "VILLA ESQUIU" },
  { id: 317, Nombre: "ALEJANDRO CENTENO" },
  { id: 318, Nombre: "ALTO DE DON BOSCO" },
  { id: 319, Nombre: "ACHAVAL PE�A" },
  { id: 320, Nombre: "BELLA VISTA" },
  { id: 321, Nombre: "LOS CIELOS" },
  { id: 322, Nombre: "LOS SOLES" },
  { id: 323, Nombre: "LOS SUEÑOS" },
  { id: 324, Nombre: "LOS ARBOLES" },
  { id: 325, Nombre: "COUNTRY ALTOS DEL CHATEAU" },
  { id: 326, Nombre: "AGENCIA CORDOBA SOLIDARIA" },
  { id: 327, Nombre: "PARQUE LICEO 3A SECCION" },
  { id: 328, Nombre: "PARQUE CAPITAL" },
  { id: 329, Nombre: "MARIANO BALCARCE" },
  { id: 330, Nombre: "VILLA SILVANO FUNES" },
  { id: 331, Nombre: "LAS FLORES" },
  { id: 332, Nombre: "HORIZONTE" },
  { id: 333, Nombre: "SAN FERNANDO" },
  { id: 334, Nombre: "IPONA" },
  { id: 335, Nombre: "LOS SAUCES" },
  { id: 336, Nombre: "NICOLAS AVELLANEDA" },
  { id: 337, Nombre: "RESIDENCIAL ARAGON" },
  { id: 338, Nombre: "QUINTAS DE SAN JORGE" },
  { id: 339, Nombre: "SAN SALVADOR" },
  { id: 340, Nombre: "DR RENE FAVALORO" },
  { id: 341, Nombre: "PUENTE BLANCO" },
  { id: 342, Nombre: "LAS DALIAS" },
  { id: 343, Nombre: "LAS PALMAS" },
  { id: 344, Nombre: "25 DE MAYO" },
  { id: 345, Nombre: "VILLA RETIRO" },
  { id: 346, Nombre: "SAN VICENTE" },
  { id: 347, Nombre: "MIRADOR" },
  { id: 348, Nombre: "RESIDENCIAL SAN JORGE" },
  { id: 349, Nombre: "SANTA ISABEL 1A SECCION" },
  { id: 350, Nombre: "RESIDENCIAL SUD" },
  { id: 351, Nombre: "LA FRANCE" },
  { id: 352, Nombre: "LAS MAGNOLIAS" },
  { id: 353, Nombre: "JOSE HERNANDEZ" },
  { id: 354, Nombre: "COUNTRY COSTA VERDE" },
  { id: 355, Nombre: "PARQUE CHATEAU CARRERAS" },
  { id: 356, Nombre: "CHATEAU CARRERAS" },
  { id: 357, Nombre: "VILLA CLARET" },
  { id: 358, Nombre: "ITUZAINGO" },
  { id: 359, Nombre: "ITUZAINGO II" },
  { id: 360, Nombre: "PATRICIOS NORTE" },
  { id: 361, Nombre: "PATRICIOS ESTE" },
  { id: 362, Nombre: "AMPLIACION GENERAL ARTIGAS" },
  { id: 363, Nombre: "EL QUEBRACHO" },
  { id: 364, Nombre: "LA FLORESTA" },
  { id: 365, Nombre: "VILLA AVALOS" },
  { id: 366, Nombre: "LAS VIOLETAS" },
  { id: 367, Nombre: "LOS FILTROS" },
  { id: 368, Nombre: "VILLA WARCALDE" },
  { id: 369, Nombre: "CO.VI.CO." },
  { id: 370, Nombre: "MIRADOR DEL CHATEAU" },
  { id: 371, Nombre: "CHATEAU CARRERAS" },
  { id: 372, Nombre: "HOGAR PROPIO" },
  { id: 373, Nombre: "GENERAL PUEYRREDON" },
  { id: 374, Nombre: "QUEBRADA DE LAS ROSAS" },
  { id: 375, Nombre: "LOS ROBLES" },
  { id: 376, Nombre: "AMPLIACION SAN PABLO" },
  { id: 377, Nombre: "SAN FELIPE" },
  { id: 378, Nombre: "RENE FAVALORO SUD" },
  { id: 379, Nombre: "RAMON J. CARCANO" },
  { id: 380, Nombre: "SAN FELIPE" },
  { id: 381, Nombre: "RAMON J CARCANO" },
  { id: 382, Nombre: "EL BOSQUE" },
  { id: 383, Nombre: "COUNTRY LOMAS DE LA CAROLINA" },
  { id: 384, Nombre: "ROCIO DEL SUR" },
  { id: 385, Nombre: "SAN RAFAEL" },
  { id: 386, Nombre: "AVENIDA" },
  { id: 387, Nombre: "VILLA QUISQUIZACATE" },
  { id: 388, Nombre: "JOSE IGNACION DIAZ 3" },
  { id: 389, Nombre: "JOSE IGNACIO DIAZ 3A SECCION" },
  { id: 390, Nombre: "23 DE ABRIL" },
  { id: 391, Nombre: "CARBO" },
  { id: 392, Nombre: "VILLA EL LIBERTADOR" },
  { id: 393, Nombre: "SANTA ROSA RESIDENCIAL" },
  { id: 394, Nombre: "MIRIZI" },
  { id: 395, Nombre: "SAN MARTIN" },
  { id: 396, Nombre: "AMPLIACION LAS PALMAS" },
  { id: 397, Nombre: "RIVERA INDARTE" },
  { id: 398, Nombre: "GUARNICION MILITAR CBA" },
  { id: 399, Nombre: "COUNTRY LAS DELICIAS" },
  { id: 400, Nombre: "PROVIDENCIA" },
  { id: 401, Nombre: "INAUDI" },
  { id: 402, Nombre: "POSTA DE VARGAS" },
  { id: 403, Nombre: "BIALET MASSE" },
  { id: 404, Nombre: "JARDIN DEL SUD" },
  { id: 405, Nombre: "SAN IGNACIO" },
  { id: 406, Nombre: "QUEBRADA DE LAS ROSAS" },
  { id: 407, Nombre: "EL VIEJO ALGARROBO" },
  { id: 408, Nombre: "VILLA RIVERA INDARTE" },
  { id: 409, Nombre: "VILLA SALDAN" },
  { id: 410, Nombre: "AMPLIACION POETA LUGONES" },
  { id: 411, Nombre: "NUEVA CORDOBA ANEXA" },
  { id: 412, Nombre: "MAIPU 1A SECCION" },
  { id: 413, Nombre: "GENERAL PAZ" },
  { id: 414, Nombre: "BAJO GENERAL PAZ" },
  { id: 415, Nombre: "JUNIORS" },
  { id: 416, Nombre: "CERRO NORTE" },
  { id: 417, Nombre: "ARGUELLO NORTE" },
  { id: 418, Nombre: "VILLA 9 DE JULIO" },
  { id: 419, Nombre: "PARQUE REPUBLICA" },
  { id: 420, Nombre: "VILLA MARTINEZ" },
  { id: 421, Nombre: "AMPLIACION SAN FERNANDO" },
  { id: 422, Nombre: "VILLA SAN ISIDRO" },
  { id: 423, Nombre: "RESIDENCIAL AMERICA" },
  { id: 424, Nombre: "AYACUCHO" },
  { id: 425, Nombre: "ALTAMIRA" },
  { id: 426, Nombre: "MAIPU 2A SECCION" },
  { id: 427, Nombre: "SARMIENTO" },
  { id: 428, Nombre: "MARIANO FRAGUEIRO" },
  { id: 429, Nombre: "AMPLIACION PANAMERICANO" },
  { id: 430, Nombre: "YOFRE NORTE" },
  { id: 431, Nombre: "SANTA CLARA DE ASIS" },
  { id: 432, Nombre: "PADRE CLARET" },
  { id: 433, Nombre: "LOS ANGELES" },
  { id: 434, Nombre: "CAMINO A VILLA POSE" },
  { id: 435, Nombre: "SACCHI" },
  { id: 436, Nombre: "VILLA CORONEL OLMEDO" },
  { id: 437, Nombre: "FERREYRA" },
  { id: 438, Nombre: "LAS CAÑUELAS" },
  { id: 439, Nombre: "PIEDRAS BLANCAS" },
  { id: 440, Nombre: "QUINTAS DE FLORES" },
  { id: 441, Nombre: "EL BALCON" },
  { id: 442, Nombre: "EL ROCIO Y LAS CIGARRAS" },
  { id: 443, Nombre: "CAMINO A 60 CUADRAS" },
  { id: 444, Nombre: "FINCAS DEL SUR" },
  { id: 445, Nombre: "GUEMES" },
  { id: 446, Nombre: "COMERCIAL" },
  { id: 447, Nombre: "TRANVIARIOS" },
  { id: 448, Nombre: "ALTO ALBERDI" },
  { id: 449, Nombre: "VILLA SAN CARLOS" },
  { id: 450, Nombre: "COUNTRY JOCKEY CLUB" },
  { id: 451, Nombre: "MALDONADO" },
  { id: 452, Nombre: "MAULLER" },
  { id: 453, Nombre: "SAN PABLO" },
  { id: 454, Nombre: "RESIDENCIAL SAN CARLOS" },
  { id: 455, Nombre: "EL REFUGIO" },
  { id: 456, Nombre: "LA SALLE" },
  { id: 457, Nombre: "CRISOL SUD" },
  { id: 458, Nombre: "CABAÑA DEL PILAR" },
  { id: 459, Nombre: "JARDIN" },
  { id: 460, Nombre: "VILLA REVOL ANEXO" },
  { id: 461, Nombre: "VILLA REVOL" },
  { id: 462, Nombre: "VILLA GENERAL URQUIZA" },
  { id: 463, Nombre: "TEODORO FELS" },
  { id: 464, Nombre: "JOSE IGNACIO RUCCI" },
  { id: 465, Nombre: "VILLA GRAN PARQUE" },
  { id: 466, Nombre: "LICEO GENERAL PAZ" },
  { id: 467, Nombre: "LICEO GENERAL PAZ" },
  { id: 468, Nombre: "MARIA LASTENIA" },
  { id: 469, Nombre: "MUTUAL DE LOS DOCENTES" },
  { id: 470, Nombre: "SMATA" },
  { id: 471, Nombre: "VILLA CENTENARIO" },
  { id: 472, Nombre: "SAN MARCELO" },
  { id: 473, Nombre: "PARQUE LATINO" },
  { id: 474, Nombre: "AMPLIACION VELEZ SARSFIELD" },
  { id: 475, Nombre: "LOS OLMOS" },
  { id: 476, Nombre: "ALTA CORDOBA" },
  { id: 477, Nombre: "DUCASSE" },
  { id: 478, Nombre: "GUIÑAZU" },
  { id: 479, Nombre: "VILLA ALICIA RISLER" },
  { id: 480, Nombre: "LA CAROLINA" },
  { id: 481, Nombre: "VALLE ESCONDIDO" },
  { id: 482, Nombre: "QUINTAS DE ITALIA" },
  { id: 483, Nombre: "CAMINO A SAN CARLOS" },
  { id: 484, Nombre: "GRANJA DE FUNES" },
  { id: 485, Nombre: "LOS BOULEVARES" },
  { id: 486, Nombre: "ESTACION FLORES" },
  { id: 487, Nombre: "AMPLIACION BENJAMIN MATIENZO" },
  { id: 488, Nombre: "TEJAS DEL SUR" },
  { id: 489, Nombre: "AMPLIACION KENNEDY" },
  { id: 490, Nombre: "KENNEDY" },
  { id: 491, Nombre: "JARDIN HIPODROMO" },
  { id: 492, Nombre: "ACOSTA" },
  { id: 493, Nombre: "COLONIA LOLA" },
  { id: 494, Nombre: "SAN JOSE" },
  { id: 495, Nombre: "PORTAL DEL JACARANDA" },
  { id: 496, Nombre: "ARGUELLO" },
  { id: 497, Nombre: "SAN RAMON" },
  { id: 498, Nombre: "ITUZAINGO ANEXO" },
  { id: 499, Nombre: "ITUZAINGO ANEXO" },
  { id: 500, Nombre: "VILLA EUCARISTICA" },
  { id: 501, Nombre: "BAJO PALERMO" },
  { id: 502, Nombre: "ESCOBAR" },
];
